// JPA entity mapping the "products" table; search_vector is generated by Postgres and left unmapped.
package com.iloveshopping.catalog;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

@Entity
@Table(name = "products")
@Getter
@Setter
public class Product {

    @Id
    @GeneratedValue
    private UUID id;

    @Column(nullable = false)
    private String name;

    @Column
    private String description;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    @Column(name = "stock_quantity", nullable = false)
    private int stockQuantity;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brand_id")
    private Brand brand;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> attributes;

    // Maintained by the trg_product_reviews_refresh_rating trigger (V6), so Java never writes them.
    @Column(name = "average_rating", insertable = false, updatable = false)
    private BigDecimal averageRating;

    @Column(name = "review_count", insertable = false, updatable = false)
    private Integer reviewCount;

    @Column(nullable = false)
    private boolean active = true;

    // Metric is the source of truth; the imperial columns are derived from it on every write.
    @Column(name = "weight_kg")
    private BigDecimal weightKg;

    @Column(name = "width_cm")
    private BigDecimal widthCm;

    @Column(name = "height_cm")
    private BigDecimal heightCm;

    @Column(name = "depth_cm")
    private BigDecimal depthCm;

    @Column(name = "weight_lbs")
    private BigDecimal weightLbs;

    @Column(name = "width_in")
    private BigDecimal widthIn;

    @Column(name = "height_in")
    private BigDecimal heightIn;

    @Column(name = "depth_in")
    private BigDecimal depthIn;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }
}
