CREATE TABLE "users" (
    "id" UUID,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "full_name" VARCHAR(255) NOT NULL,
    "avatar_url" VARCHAR(255),
    "auth_provider" VARCHAR(255) NOT NULL DEFAULT 'LOCAL',
    "role" VARCHAR(255) NOT NULL DEFAULT 'CUSTOMER' CHECK("role" IN ('CUSTOMER','ADMIN')),
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "two_factor_enabled" BOOLEAN NOT NULL DEFAULT false,
    "two_factor_secret" VARCHAR(255),
    "two_factor_backup_codes" VARCHAR(255),
    "oauth_provider_id" VARCHAR(255),
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY("id")
);


CREATE TABLE "categories" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "slug" VARCHAR(255) NOT NULL UNIQUE,
    "parent_id" INTEGER,
    "active" BOOLEAN DEFAULT true,
    PRIMARY KEY("id")
);


CREATE UNIQUE INDEX "uq_categories_parent_name"
ON "categories" ("parent_id", "name");

CREATE UNIQUE INDEX "uq_categories_root_name"
ON "categories" ("name")
WHERE "parent_id" IS NULL;

CREATE TABLE "brands" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "slug" VARCHAR(255) NOT NULL UNIQUE,
    "logo_url" VARCHAR(255),
    PRIMARY KEY("id")
);


CREATE TABLE "products" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "price" DECIMAL(10,2) NOT NULL,
    "stock_quantity" INTEGER NOT NULL DEFAULT 0,
    "category_id" INTEGER NOT NULL,
    "brand_id" INTEGER,
    "attributes" JSONB,
    "search_vector" TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))
    ) STORED,
    "average_rating" NUMERIC(3,2),
    "review_count" INTEGER DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "weight_kg" NUMERIC,
    "width_cm" NUMERIC,
    "height_cm" NUMERIC,
    "depth_cm" NUMERIC,
    "weight_lbs" NUMERIC,
    "width_in" NUMERIC,
    "height_in" NUMERIC,
    "depth_in" NUMERIC,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY("id")
);


CREATE TABLE "product_images" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "product_id" UUID NOT NULL,
    "url" VARCHAR(255) NOT NULL,
    "alt_text" TEXT,
    "display_order" INTEGER,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY("id")
);


CREATE TABLE "product_reviews" (
    "id" UUID NOT NULL,
    "product_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "rating" INTEGER NOT NULL CHECK("rating" BETWEEN 1 AND 5),
    "title" VARCHAR(255) NOT NULL,
    "body" TEXT NOT NULL,
    "verified_purchase" BOOLEAN NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);


CREATE UNIQUE INDEX "uq_product_reviews_product_user"
ON "product_reviews" ("product_id", "user_id");

ALTER TABLE "categories"
ADD FOREIGN KEY("parent_id") REFERENCES "categories"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "products"
ADD FOREIGN KEY("category_id") REFERENCES "categories"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "products"
ADD FOREIGN KEY("brand_id") REFERENCES "brands"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "product_images"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "product_reviews"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "product_reviews"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
